name: Pull Request
description: Submit a pull request
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a pull request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the changes in this PR
    validations:
      required: true
  - type: input
    id: issue
    attributes:
      label: Related Issue
      description: Link to any related issues (e.g., Fixes #123)
  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      options:
        - Bug fix (non-breaking)
        - New feature (non-breaking)
        - Breaking change
        - Documentation update
        - Performance improvement
        - Code refactoring
        - Test addition/update
        - Other
    validations:
      required: true

  - type: checkboxes
    id: tests
    attributes:
      label: Testing Performed
      options:
        - label: Added new unit tests (if applicable)
        - label: Updated existing tests (if applicable)
        - label: Manually tested functionality
        - label: Ran R CMD check with no ERRORs or WARNINGs
        - label: Ran devtools::test()
  - type: checkboxes
    id: license
    attributes:
      label: License Agreement
      description: By submitting this pull request, you agree to transfer the license of your code to the project. Please note that the project's license terms may change in the future.
      options:
        - label: I agree that my contribution is licensed to the project and can be modified as needed, and I understand that the project's license terms may change over time
          required: true
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My code follows the style guidelines of this project
        - label: I have updated documentation accordingly
        - label: My changes pass all tests
        - label: I have updated NEWS.md (if applicable)
        - label: I have updated DESCRIPTION (if applicable)
        - label: I have regenerated roxygen2 documentation (if applicable)
    validations:
      required: true
